### ISSUE TITLE
Initial paper on Congential CHB

### ISSUE THREAD

**Issue by docsteveharris** [datascibc/cheryl-phd#24]
Approx 17 patients

- [ ] send missingness to walkers and SH
- [ ] organise trio + CA meeting 
- [ ] trio + CA meeting
- [ ] Confirm topic for first paper

**Comment by docsteveharris** [comment]
This does not seem doable until we have external data on the delivery outcomes.
Put on hold for now

**Comment by tagimoucia-cheryl** [comment]
- [ ] send missingness to walkers and SH
- [ ] organise trio + CA meeting 
- [ ] trio + CA meeting
- [ ] Confirm topic for first paper
